### PR TITLE
wasmate: accept .lcomm with missing alignment argument.

### PR DESCRIPTION
**Pull request by ncbray**

### CODE REVIEW

**Comment by jfbastien** [comment]
lgtm

**Comment by sunfishcode** [comment]
What tool is emitting .lcomm without an alignment?

**Comment by sunfishcode** [comment]
Also, looking at what llvm-mc does, a missing alignment argument is not equivalent to no alignment.

**Comment by sunfishcode** [comment]
[The gas manual saos this about .comm](https://sourceware.org/binutils/docs/as/Comm.html#Comm):

>  If no alignment is specified, as will set the alignment to the largest power of two less than or equal to the size of the symbol, up to a maximum of 16 on ELF, or the default section alignment of 4 on PE1.

and I assume the same is meant to apply to .lcomm. It's not clear what this means for wasm.

**Comment by ncbray** [comment]
I have only seen the missing alignment field for .lcomm of size 1, so far.  Generally, everything else has an explicit alignment.

**Comment by sunfishcode** [comment]
Where did you see it?

**Comment by ncbray** [comment]
Output from torture tests.
I'll change it to align to natural power-of-two tomorrow.

**Comment by ncbray** [comment]
OK, funny.

https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.c-torture/execute/981206-1.c

This outputs:
.type x,@object
.lcomm x,1
.type y,@object
.lcomm y,1

Which is highly suspect, because x and y are not size 1.

(Also, they are technically not in the data segment, which is naively unexpected.)

**Comment by sunfishcode** [comment]
If you're compiling with -O2, LLVM shrinks them to size 1.

Ah, I was wrong [above](https://github.com/WebAssembly/experimental/pull/57#issuecomment-164617067). LLVM appears to treat a missing alignment as a byte alignment of 1, while GAS does the rule quoted above. So they're incompatible.

**Comment by sunfishcode** [comment]
I am now back to thinking the current patch lgtm. The incompatibility is surprising, but we can move forward.

I filed https://llvm.org/bugs/show_bug.cgi?id=25837 against LLVM concerning the incompatibility with GAS.

**Pull request merged**
