### PR TITLE
Support for addresses with constant offsets.

### PR DESCRIPTION
**Pull request by sunfishcode**
This teaches wasmate about folded constant offsets, foo+47 as a constant rather than requiring an add operation. This is in preparation for implementing this optimization in LLVM.

### CODE REVIEW

**Comment by jfbastien** [comment]
Is that in [AstSemantics.md](https://github.com/WebAssembly/design/blob/master/AstSemantics.md)? I think it makes sense to support something of the sort, but I'd make sure consumers can handle it before wasmate starts generating it.

@binji does your assembler support something like this?

**Comment by sunfishcode** [comment]
Since symbols are resolved before we produce the final form, AstSemantics.md doesn't have to know anything about it. See test/expected-output/offset-folding.wast file for examples. The only case where it isn't resolved away is unresolved global variable symbols, but wasm doesn't actually support those anyway.

**Comment by jfbastien** [comment]
Ah OK, `$x+188` only appears in the sexpr because it's still unresolved which should happen in general (`$x` also shouldn't appear in regular usage). SOrry for being dense, weekend + packing bags makes for easy think-o's. If that's the case then could you add a comment to explain? lgtm with a comment.

**Comment by sunfishcode** [comment]
Comment added.

**Pull request merged**
