### PR TITLE
Fix exports of addresses in the data segment.

### PR DESCRIPTION
**Pull request by ncbray**
Due to the lack of tests and that I don't know of any uses cases, I'd advocate going even farther and removing these exports.

### CODE REVIEW

**Comment by binji** [comment]
What's the bug? I believe without this we'll never generate functions that can be exported to JavaScript.

**Comment by ncbray** [comment]
Digging deeper, it looks like the issue is this mechanism is triggering for both functions and global variables.  This fix de-symbolizes the global variables (good) but then sexpr-wasm still chokes because it interprets the constant as a function export.  Uhg.

**Comment by binji** [comment]
Global variables should never be exported, (export ...) only applies to functions. I guess wasmate needs to be more intelligent about what the label resolves to.

**Comment by ncbray** [comment]
Fix in progress, give me a sec.  I thought exporting globals was intentional, but it looks like it very much is not.

**Comment by ncbray** [comment]
Fixed and documented.

**Comment by binji** [comment]
Great, lgtm

**Pull request merged**
