### PR TITLE
wasmate: import declares result

### PR DESCRIPTION
**Pull request by jfbastien**
It was declaring it with return instead, which is inconsistent with function declarations.

### CODE REVIEW

**Comment by jfbastien** [comment]
@binji it looks like either was accepted by sexpr-wasm, that's probably a bug?

**Comment by kripken** [comment]
lgtm

**Comment by binji** [comment]
@jfbastien I don't think so, I just tested this and got:
```
parse/module/bad-import-return.txt:2:30: syntax error, unexpected RETURN, expecting TYPE or PARAM or RESULT
```

**Comment by jfbastien** [comment]
Ah right, I hadn't regenerated the `.wast` tests! Updated the list of expected failures:
  https://github.com/WebAssembly/sexpr-wasm-prototype/pull/14

**Pull request merged**
